# Generated by Django 5.0.14 on 2026-06-28 20:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FRAClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claim_identifier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('claim_type', models.CharField(choices=[('IFR', 'Individual Forest Right'), ('CFR', 'Community Forest Right'), ('CR', 'Community Resource Right')], max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=16)),
                ('area_hectares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('claim_date', models.DateField()),
                ('forest_location_geojson', models.JSONField(blank=True, null=True)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('dss_recommendations_json', models.JSONField(blank=True, default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='geo.district')),
                ('tribal_community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='geo.tribalcommunity')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='geo.village')),
            ],
            options={
                'db_table': 'fra_claim',
            },
        ),
        migrations.CreateModel(
            name='DSSRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recommendation_type', models.CharField(max_length=32)),
                ('confidence_score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('supporting_factors', models.JSONField(blank=True, default=list)),
                ('fra_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dss_recommendations', to='claims.fraclaim')),
            ],
            options={
                'db_table': 'dss_recommendation',
            },
        ),
        migrations.AddIndex(
            model_name='fraclaim',
            index=models.Index(fields=['status', 'created_at'], name='fra_claim_status_1c1004_idx'),
        ),
        migrations.AddIndex(
            model_name='fraclaim',
            index=models.Index(fields=['district', 'status'], name='fra_claim_distric_9d5b37_idx'),
        ),
        migrations.AddIndex(
            model_name='fraclaim',
            index=models.Index(fields=['tribal_community', 'status'], name='fra_claim_tribal__1d13c2_idx'),
        ),
    ]
