# Generated by Django 5.0.14 on 2026-06-28 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('row_counts_json', models.JSONField(default=dict)),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ops_data_snapshot',
            },
        ),
        migrations.CreateModel(
            name='DeadLetterTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('task_name', models.CharField(max_length=120)),
                ('args_json', models.JSONField(default=list)),
                ('kwargs_json', models.JSONField(default=dict)),
                ('error_message', models.TextField()),
                ('retries', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ops_dead_letter',
            },
        ),
        migrations.CreateModel(
            name='ExternalSystemIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('system_name', models.CharField(max_length=80)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('records_synced_count', models.IntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('error_message_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ops_external_integration',
            },
        ),
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('task_name', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'ops_batch_job',
                'indexes': [models.Index(fields=['task_name', 'created_at'], name='ops_batch_j_task_na_f4661d_idx')],
            },
        ),
    ]
