# Generated by Django 5.0.14 on 2026-06-28 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSITION', 'State transition'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_role', models.CharField(max_length=32)),
                ('previous_state_json', models.JSONField(blank=True, null=True)),
                ('new_state_json', models.JSONField(blank=True, null=True)),
                ('change_diff_json', models.JSONField(blank=True, null=True)),
                ('reason_text', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('cryptographic_signature', models.CharField(max_length=128)),
                ('previous_log_signature', models.CharField(blank=True, max_length=128, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='audit_log_entity__8f3254_idx'), models.Index(fields=['actor_id', 'created_at'], name='audit_log_actor_i_2ba9f4_idx')],
            },
        ),
    ]
