# Generated by Django 5.0.14 on 2026-06-28 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_key', models.CharField(max_length=512)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('fra_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='claims.fraclaim')),
            ],
            options={
                'db_table': 'document_attachment',
                'indexes': [models.Index(fields=['fra_claim', 'created_at'], name='document_at_fra_cla_91a7d4_idx')],
            },
        ),
    ]
