# Generated by Django 5.0.14 on 2026-06-28 20:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('FIELD_OFFICER', 'Field Officer'), ('BLOCK_OFFICIAL', 'Block Official'), ('DISTRICT_ADMIN', 'District Administrator'), ('STATE_COORDINATOR', 'State Coordinator'), ('ML_RESEARCHER', 'ML Researcher'), ('SUPERUSER', 'Superuser'), ('ML_SYSTEM', 'ML System (automated)')], default='FIELD_OFFICER', max_length=32)),
                ('assigned_states', models.JSONField(blank=True, default=list)),
                ('assigned_districts', models.JSONField(blank=True, default=list)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, default='', max_length=128)),
                ('password_last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'account_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FIELD_OFFICER', 'Field Officer'), ('BLOCK_OFFICIAL', 'Block Official'), ('DISTRICT_ADMIN', 'District Administrator'), ('STATE_COORDINATOR', 'State Coordinator'), ('ML_RESEARCHER', 'ML Researcher'), ('SUPERUSER', 'Superuser'), ('ML_SYSTEM', 'ML System (automated)')], max_length=32)),
                ('permission_code', models.CharField(choices=[('VIEW_CLAIM', 'View claim'), ('CREATE_CLAIM', 'Create claim'), ('EDIT_CLAIM', 'Edit claim'), ('SUBMIT_CLAIM', 'Submit claim'), ('REVIEW_CLAIM', 'Move claim to review'), ('APPROVE_CLAIM', 'Approve claim'), ('REJECT_CLAIM', 'Reject claim'), ('VIEW_ANALYTICS', 'View analytics')], max_length=32)),
            ],
            options={
                'db_table': 'account_role_permission',
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]
