# Generated by Django 5.0.14 on 2026-06-28 20:42

import apps.common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
