# Generated by Django 6.0.6 on 2026-06-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mfa_secret_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pii_erased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
