apiVersion: v1
kind: Secret
metadata:
  name: fra-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "REPLACE_VIA_SEALED_SECRET_OR_KMS"
  AUDIT_LOG_SECRET: "REPLACE_VIA_SEALED_SECRET_OR_KMS"
  ENCRYPTION_KEY_V1: "REPLACE_VIA_SEALED_SECRET_OR_KMS"
  DATABASE_URL: "postgis://fra:REPLACE@postgis:5432/fra_atlas"
