# Generated by Django 6.0.6 on 2026-06-29 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject_user_id', models.UUIDField()),
                ('request_type', models.CharField(choices=[('ACCESS', 'Access / portability'), ('ERASURE', 'Erasure')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('legal_basis_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'privacy_data_subject_request',
            },
        ),
    ]
