# Generated by Django 5.0.14 on 2026-06-28 20:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('district_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name_english', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=64)),
                ('tribal_population', models.PositiveIntegerField(default=0)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_category', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16, null=True)),
                ('last_risk_update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geo_district',
                'indexes': [models.Index(fields=['state', 'district_code'], name='geo_distric_state_a4d55c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TribalCommunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name_english', models.CharField(max_length=128)),
                ('territory', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='geo.district')),
            ],
            options={
                'db_table': 'geo_tribal_community',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('village_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('village_name', models.CharField(max_length=128)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='geo.district')),
            ],
            options={
                'db_table': 'geo_village',
            },
        ),
    ]
