# Generated by Django 5.0.14 on 2026-06-28 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorCorrelationMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('matrix_json', models.JSONField()),
                ('method', models.CharField(default='pearson', max_length=16)),
                ('factors', models.JSONField(default=list)),
                ('sample_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'factor_correlation_matrix',
            },
        ),
        migrations.CreateModel(
            name='RiskPredictionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('roc_auc', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('pr_auc', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('feature_importance_json', models.JSONField(blank=True, default=dict)),
                ('feature_list', models.JSONField(blank=True, default=list)),
                ('model_binary_blob', models.BinaryField(blank=True, null=True)),
                ('explainer_blob', models.BinaryField(blank=True, null=True)),
                ('signature_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('training_metrics_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'risk_prediction_model',
            },
        ),
        migrations.CreateModel(
            name='DistrictRiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('model_version', models.CharField(blank=True, default='', max_length=32)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('risk_category', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('risk_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('pc1', models.FloatField(blank=True, null=True)),
                ('pc2', models.FloatField(blank=True, null=True)),
                ('factors_json', models.JSONField(blank=True, default=dict)),
                ('shap_explanation_json', models.JSONField(blank=True, default=dict)),
                ('prediction_timestamp', models.DateTimeField(db_index=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_snapshots', to='geo.district')),
            ],
            options={
                'db_table': 'district_risk_snapshot',
                'indexes': [models.Index(fields=['district', 'prediction_timestamp'], name='district_ri_distric_e37f1d_idx')],
            },
        ),
    ]
