# Generated by Django 6.0.6 on 2026-06-29 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('pushed_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('payload_sha256', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'sync_batch',
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entity_type', models.CharField(max_length=40)),
                ('client_ref', models.CharField(max_length=128)),
                ('reason', models.CharField(max_length=200)),
                ('client_payload', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncbatch')),
            ],
            options={
                'db_table': 'sync_conflict',
            },
        ),
    ]
