# Generated by Django 5.0.14 on 2026-06-28 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_type', models.CharField(max_length=40)),
                ('export_format', models.CharField(default='CSV', max_length=8)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_by', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_job',
            },
        ),
    ]
